variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

stages:
  - build
  - test
  - evaluate

python_build:
  stage: build
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:python
  script:
    - python -m build --wheel .
  artifacts:
    paths:
      - dist/*.whl

# python_tests:
#   stage: test
#   image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:python
#   needs:
#     - python_build
#   script:
#     - pip install dist/*.whl[test]
#     - coverage run -m pytest graph_impute/tests
#     - coverage report -m

cpp_unit_tests:
  stage: test
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:cpp
  needs: []
  script:
    - mkdir build && cd build
    - cmake -GNinja -DBUILD_TESTS=ON ..
    - ninja
    - ./GraphTest
    - ./KNNImputerTest
    - ./LouvainTest
    - ./CommunityImputerTest
    - ./LinearAlgebraTest
    - ./NegativeSamplerTest
    - ./DeepWalkTest
    - gcovr -r ../  -e '.*/extlibs/.*'

evaluate:
  stage: evaluate
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:python
  timeout: 2h
  allow_failure: true
  needs:
    - python_build
  parallel:
    matrix:
      - STRATEGY: ["knn", "community", "deepwalk"]
        DATASET: ["amazon", "cora", "genius", "github", "twitch"]
  script:
    - pip install dist/*.whl
    - graph-impute --strategy ${STRATEGY} --dataset ${DATASET} --time --evaluate

plot:
  stage: evaluate
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:python
  timeout: 2h
  when: manual
  needs:
    - python_build
  script:
    - pip install dist/*.whl[plot]
    - python -I -m semproject.evaluation_plots
  artifacts:
    paths:
      - "*.png"
