variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

stages:
  - build
  - evaluate

cpp_unit_tests:
  stage: build
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:cpp
  script:
    - mkdir build && cd build
    - cmake -GNinja -DBUILD_TESTS=ON ..
    - ninja
    - ./GraphTest
    - ./KNNImputerTest
    - ./LouvainTest
    - ./LouvainImputerTest
    - ./LinearAlgebraTest
    - ./NegativeSamplerTest
    - ./DeepWalkTest
    - gcovr -r ../  -e '.*/extlibs/.*'

python_build:
  stage: build
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:python
  script:
    - python -m build --wheel .
  artifacts:
    paths:
      - dist/*.whl

evaluate:
  stage: evaluate
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:python
  timeout: 2h
  allow_failure: true
  needs:
    - python_build
  script:
    - pip install dist/*.whl
    - evaluate --all

plot:
  stage: evaluate
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:python
  timeout: 2h
  when: manual
  needs:
    - python_build
  script:
    - pip install dist/*.whl
    - python -I -m semproject.evaluation_plots
  artifacts:
    paths:
      - "*.png"
