variables:
  GIT_SUBMODULE_STRATEGY: recursive

cpp_unit_tests:
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:cpp
  script:
    - mkdir build && cd build
    - cmake -GNinja -DBUILD_TESTS=ON ..
    - ninja
    - ./GraphTest
    - ./KNNImputerTest
    - gcovr -r ../  -e '.*/extlibs/.*'

python_build:
  image: gitlab.informatik.hu-berlin.de:4567/axkoro/sempro:python
  script:
    - set -e
    - python3 -m venv pyenv && . pyenv/bin/activate
    - pip3 install --upgrade pip
    - pip install -e .
    # - coverage run -m unittest discover -v semproject/testing
    # - coverage report -m